### ISSUE TITLE
cannot increment file index and cannot parse timestamp

### ISSUE THREAD

**Issue by mr04vv** [eure/kamimai#15]
When I create migration file, not incremented file index.
In addition, not parse timestamp.
eg.)
![2019-01-06 0 02 56](https://user-images.githubusercontent.com/24749358/50725804-b2ffc400-1146-11e9-911a-42fea1d90b10.png)
![2019-01-06 0 09 12](https://user-images.githubusercontent.com/24749358/50725819-518c2500-1147-11e9-9014-177606f6612d.png)

**Comment by kaneshin** [comment]
Merged
